### ISSUE TITLE
Default option in schema not populated to property.

### ISSUE THREAD

**Issue by nmarus** [fastify/fastify-env#34]
Using the example on the README.md

```js
const fastify = require('fastify')()
const fastifyEnv = require('fastify-env')

const schema = {
  type: 'object',
  required: [ 'PORT' ],
  properties: {
    PORT: {
      type: 'string',
      default: 3000
    }
  }
}

const options = {
  confKey: 'config', // optional
  schema: schema,
}
fastify.register(fastifyEnv, options, function (err) {
   // or fastify[options.confKey]
  console.log(fastify.config)
  // output: { PORT: 3000 }
})
```

Nothing is logged to console and it seems that the default key of the schema properties is not getting applied to the resulting object.

**Comment by allevo** [comment]
Hi!
thanks for reporting this.

I think the example in readme is pretty old.

If you try this:
```js
const fastify = require('fastify')()
const fastifyEnv = require('fastify-env')

const schema = {
  type: 'object',
  required: [ 'PORT' ],
  properties: {
    PORT: {
      type: 'string',
      default: 3000
    }
  }
}

const options = {
  confKey: 'config', // optional
  schema: schema,
}

fastify.ready(function () {
   // or fastify[options.confKey]
  console.log(fastify.config)
  // output: { PORT: 3000 }
})
```

the log appears.

Would you mind to send a PR to fix the doc?

**Comment by nmarus** [comment]
Thanks! Will do!

**Comment by allevo** [comment]
Closed by #35

**Comment by astesio** [comment]
I can't use outside ready function ?
Ex: If I need use some environment variable inside some route, how can I use in this case ? In my example his always undefined, but inside the ready function his come the value right.

**Comment by allevo** [comment]
@astesio 
```js
const fastify = require('fastify')()
const fastifyEnv = require('fastify-env')

const schema = {
  type: 'object',
  required: [ 'PORT' ],
  properties: {
    PORT: {
      type: 'string',
      default: 3000
    }
  }
}

const options = {
  schema: schema
}

fastify.get('/', function (request, reply) {
  reply.send(this.config)
})
```

Have you tried this?

Anyway, please consider to open a new issue if the problem persist

**Comment by astesio** [comment]
Thanks,
yes it's work, but when I use this form I have problem.

`'use strict'

const path = require('path')

require('dotenv').config()
const Fastify = require('fastify')
const AutoLoad = require('fastify-autoload')

async function buildFastify (opts) {
  const fastify = Fastify(opts)
  fastify.register(AutoLoad, { dir: path.join(__dirname, 'middlewares') })
  fastify.register(AutoLoad, { dir: path.join(__dirname, 'plugins') })
  fastify.register(AutoLoad, { dir: path.join(__dirname, 'services'),
    options: {
      prefix: '/api'
    }
  })

  fastify.ready((err) => {
    if (err) console.error(err)
    // console.log(fastify.config)
  })
  // console.log(fastify.config) // undefined
  try {
    // PROBLEM HERE
    await fastify.listen(this.config.FASTIFY_PORT, process.env.FASTIFY_ADDRESS)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  return fastify
}

if (process.env.FASTIFY_NODE_ENV === 'test') {
  module.exports = buildFastify
} else {
  buildFastify({
    logger: true
  })
}
` 
I think this error happen because I don't have the same scope, but I do no change my function, so thanks man.
