### ISSUE TITLE
usability issue and major refactoring

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-env#48]
I'm thinking the usage of this library is not providing the best user experience for Fastify users.

I've seen the following:
I think we should be recommending a synchronous approach.

```js
const fp = require("fastify-plugin")
const fastifyEnv = require("fastify-env")

module.exports = fp(async (fastify, opts) => {
  fastify.register(fastifyEnv, {
    schema: {
      type: "object",
      required: ["PG_URL"],
      properties: {
        PG_URL: {
          type: "string",
          format: "uri"
        }
      }
    },
    confKey: "pgconfig",
    data: opts,
    dotenv: true
  })

  // this is extremely complicated to write and "guess"
  fastify.register(fp(async fastify => {
    fastify.register(require("fastify-postgres"), {
      connectionString: fastify.pgconfig.PG_URL
    })
  }))
})
```

I think we should aim for:

```js
const fp = require("fastify-plugin")
const env = require("validate-env") // different module

module.exports = fp(async (fastify, opts) => {
  const config = env({
    schema: {
      type: "object",
      required: ["PG_URL"],
      properties: {
        PG_URL: {
          type: "string",
          format: "uri"
        }
      }
    },
   data: opts,
   dotenv: true
  })

    fastify.register(require("fastify-postgres"), {
      connectionString: config.PG_URL
    })
})
```

Then this module could use the new module to add a config property.

What do you think @allevo?

**Comment by allevo** [comment]
It's ok for me.

**Comment by kurtmilam** [comment]
New `fastify` user report:

First, thanks for the work you've done on this plugin.

I agree with @mcollina - the way this plugin works is unintuitive for the new user. I think it should either be updated to use a synchronous approach (bringing it in line with other `fastify` plugins I've tried out), or else the docs should be updated to show the user how to register the plugin and then use the `fastify.config` in the `fastify.listen` invocation.

I set up `fastify` for the first time yesterday evening for a side project. I registered a few plugins and created a few working routes very quickly. Overall, I found the API very intuitive and nice to use. The developer experience was pleasant, and I'm looking forward to using `fastify`.

The only exception was the `fastify-env` plugin. After having successfully registered and used 3 other plugins (`cors`, `postgres` and `swagger`) quickly and with zero issues, I was surprised to find that `fastify-env` didn't follow the API of the other plugins I had successfully configured and registered.

Unfortunately, the `fastify-env` docs show a 'toy' example, whereby the plugin is registered and the config is logged, rather than an example whereby the plugin is registered and the config is used by another plugin or in `fastify.listen`.

I'd like to note that I came across two StackOverflow questions ([1](https://stackoverflow.com/questions/50731931/), [2](https://stackoverflow.com/questions/56428947/)) about this question.

I messed around with `.after` a little before deciding to ditch this plugin in favor `dotenv`, at least temporarily, since I'm working on a side project and find the plugin API unintuitive.

For reference, here are the last few lines of my `index.js`, to show how I'm starting the server. `fastify.config.port` works here because I'm using `dotenv` rather than `fastify-env`. This is largely lifted from the official docs:
```javascript
const start = async () => {
  try {
    await fastify.listen(fastify.config.PORT)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}

start()
```

**Comment by mcollina** [comment]
I've extracted https://github.com/fastify/env-schema, and I use that instead of this module, for the reasons you are mentioning.

**Comment by kurtmilam** [comment]
Thanks @mcollina ! I should have looked at the source of this plugin before commenting on the issue.

I'll use `env-schema`, as well. In my opinion, it would be best for new adopters if the `fastify` org either deprecated this plugin or noted that `env-schema` is the preferred solution for those who'd prefer a synchronous API.

**Comment by elliottross23** [comment]
I just added an ```await``` to the register line and it works just fine. Obviously not ideal but it works!

```await fastify.register(require('fastify-env'), {})```

**Comment by climba03003** [comment]
> 
> 
> I just added an `await` to the register line and it works just fine. Obviously not ideal but it works!
> 
> `await fastify.register(require('fastify-env'), {})`

NodeJS require ```.mjs``` extension for top-level await.
The best solution should be wrapping each plugin with ```fastify-plugin``` which can resolve the problem env is not appended to fastify instance.

**Comment by arvi** [comment]
As a newbie in fastify, I'm confused on how exactly I can use this package. I thought that it will be available in `routes` as `fastify.config`, however, it wasn't. So next, I try adding a decorator, and still can't get it to work

```js
'use strict'

const fp = require('fastify-plugin')

const schema = {
  type: 'object',
  required: [ 'KEY_ONE', 'KEY_TWO' ],
  properties: {
    KEY_ONE: {
      type: 'string',
      default: '1'
    },
    KEY_TWO: {
      type: 'string',
      default: '2'
    }
  }
}

module.exports = fp(async function (fastify, opts) {
  fastify
  .register(require('fastify-env'), { schema })
  .ready((err) => {
    if (err) console.error(err)

    console.log(fastify.config) // outputs: { KEY_ONE: '1', KEY_TWO: '2' } but undefined when used in routes as fastify.config

    fastify.decorate('appConfig', fastify.config) // also returns undefined when used in routes as fastify.appConfig
  })
})
```

I created my project using `fastify-cli` and in version 3.0 🤔

**Comment by mcollina** [comment]
For all of you that you are finding this confusing, use https://github.com/fastify/env-schema. It fits your idea on how this should work better.

---

You need to register the above plugin _before_ all the others. In fastify-cli, you do that by putting it in the `plugins/` folder.

Note that:

```js
'use strict'

const fp = require('fastify-plugin')

const schema = {
  type: 'object',
  required: [ 'KEY_ONE', 'KEY_TWO' ],
  properties: {
    KEY_ONE: {
      type: 'string',
      default: '1'
    },
    KEY_TWO: {
      type: 'string',
      default: '2'
    }
  }
}

module.exports = fp(async function (fastify, opts) {
  await fastify.register(require('fastify-env'), { schema })
  console.log(fastify.config) // outputs: { KEY_ONE: '1', KEY_TWO: '2' } but undefined when used in routes as fastify.config
})
```

**Comment by arvi** [comment]
@mcollina  Yep that's what I did after generating project via `fastify-cli`. I'll just resort to the usual env implementation for now and not use `fastify-env`. Can't make it to work. 🤣

```
|- plugins
|--- env.plugin.js (copied support.js content to register as plugin and followed fastify-env docs)
|--- support.js
|- routes
|--- root.js (fastify.log.info the config in the handler section and returns undefined)
```

**Comment by arvi** [comment]
@mcollina Oh wait up. What you suggested worked!

```js
module.exports = fp(async function (fastify, opts) {
  await fastify.register(require('fastify-env'), { schema })
  console.log(fastify.config) // outputs: { KEY_ONE: '1', KEY_TWO: '2' }
})
```

I was using `fastify.log.info` instead of `console` that's why it's returning undefined in the router. When I use console, yep it's working. Thanks for the help.
